local Items = {}

Items.items = {
    ["el_materials_pure_iron"] = {},
    ["el_materials_pure_copper"] = {},
    ["el_materials_pure_aluminum"] = {},
    ["el_materials_ceramic"] = {},
    ["el_materials_ALK"] = {},
    ["fi_materials_empty_solution"] = {},
    ["fi_materials_solution"] = {},
    ["fi_materials_rich_powder"] = {},
    ["fi_materials_natural_fiber"] = {},
    ["fi_materials_glass_fiber"] = {},
    ["fi_materials_glass"] = {},
    ["fi_materials_flourite"] = {},
    ["fi_materials_pure_gold"] = {},
    ["fi_materials_pure_titan"] = {},
    ["fi_materials_pure_neodym"] = {},
    ["fi_materials_gold"] = {},
    ["fi_materials_neodym"] = {},
    ["fi_materials_titan"] = {},
    ["fi_materials_NFK"] = {},
    ["fi_materials_GFK"] = {},
    ["fi_materials_waste"] = {},
    ["fi_thorium232_item"] = {},
    ["fi_uranium233_item"] = {},
    ["fi_plutonium239_item"] = {},
    ["fi_crushed_iron_item"] = {},
    ["fi_crushed_copper_item"] = {},
    ["fi_crushed_aluminum_item"] = {},
    ["fi_crushed_lithium_item"] = {},
    ["fi_crushed_crystal_item"] = {},
    ["fi_catalyst_crystal_item"] = {},
    ["fi_base_crystal_item"] = {},
    ["fi_crushed_coal_item"] = {},
    ["fi_industrial_steel_blend_item"] = {},
    ["fi_industrial_steel_item"] = {},
    ["fi_compound_material_item"] = {},
    ["fi_crushed_glass_item"] = {},
    ["fi_crushed_stone_item"] = {},
    ["fi_crushed_uranium_item"] = {},
    ["fi_energy_crystal_item"] = {},
    ["fi_energy_crystal_charged_item"] = {},

    ["fu_materials_energy_crystal"] = {},
    ["fu_materials_refined_crystal"] = {},
    ["fu_materials_pure_lead"] = {},
    ["fu_materials_KFK"] = {},
    ["fu_materials_TIM"] = {},
    ["fu_materials_magnet"] = {},
    ["fu_materials_carbon_fiber"] = {},
    ["fu_materials_plasma_card"] = {},
    ["fu_materials_laser_card"] = {},
    ["fu_materials_magnet_card"] = {},
    ["fu_materials_fusion_card"] = {},
    ["fu_materials_empty_container"] = {},
    ["fu_materials_charged_container"] = {},
    ["fu_crushed_lead_item"] = {},

    ["el_aluminum_ore_item"] = {},
    ["el_lithium_ore_item"] = {},
    ["el_energy_crystal_item"] = {},
    ["el_aluminum_item"] = {},
    ["el_lithium_item"] = {},
    ["el_lithium_battery"] = {},

    ["fu_lead_ore_item"] = {},
    ["fu_lead_item"] = {},
    ["fu_space_probe_data_card_1_item"] = {},
    ["fu_space_probe_data_card_2_item"] = {},
    ["fu_space_probe_data_card_3_item"] = {},
    ["fu_space_probe_down_matter_item"] = {},
    ["fu_space_probe_up_matter_item"] = {},

    ["green-wire"] = {},
    ["red-wire"] = {}
}

return Items
